name: AntiUGFarm
main: de.craftlancer.antiugfarm.AntiUGFarm
version: 0.4
description: Prevents placing plants in the underground.
permissions:
  antiugfarm.ignore:
    description: You can create farm everywhere
    default: false